/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as ConcreteCleaningRouteImport } from './routes/concrete-cleaning'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DrivewayCleaningRouteImport } from './routes/driveway-cleaning'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PaintingServiceRouteImport } from './routes/painting-service'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResidentialRouteImport } from './routes/residential'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RoofWashingRouteImport } from './routes/roof-washing'
import { Route as SidingCleaningRouteImport } from './routes/siding-cleaning'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogBestTimeOfYearToPressureWashHomeMooresvilleNcRouteImport } from './routes/blog/best-time-of-year-to-pressure-wash-home-mooresville-nc'
import { Route as BlogCommercialPressureWashingLakeNormanRouteImport } from './routes/blog/commercial-pressure-washing-lake-norman'
import { Route as BlogDumpsterPadCleaningRestaurantsLakeNormanRouteImport } from './routes/blog/dumpster-pad-cleaning-restaurants-lake-norman'
import { Route as BlogHowMuchDoesPressureWashingCostMooresvilleNcRouteImport } from './routes/blog/how-much-does-pressure-washing-cost-mooresville-nc'
import { Route as BlogHowOftenToPressureWashHouseNcRouteImport } from './routes/blog/how-often-to-pressure-wash-house-nc'
import { Route as BlogHowToCleanConcreteDrivewayNcClayRouteImport } from './routes/blog/how-to-clean-concrete-driveway-nc-clay'
import { Route as BlogHowToRemoveAlgaeRoofLakeNormanRouteImport } from './routes/blog/how-to-remove-algae-roof-lake-norman'
import { Route as BlogPressureWashingVsSoftWashingRouteImport } from './routes/blog/pressure-washing-vs-soft-washing'
import { Route as ServiceAreasIndexRouteImport } from './routes/service-areas/index'
import { Route as ServiceAreasCorneliusNcRouteImport } from './routes/service-areas/cornelius-nc'
import { Route as ServiceAreasDavidsonNcRouteImport } from './routes/service-areas/davidson-nc'
import { Route as ServiceAreasDenverNcRouteImport } from './routes/service-areas/denver-nc'
import { Route as ServiceAreasHuntersvilleNcRouteImport } from './routes/service-areas/huntersville-nc'
import { Route as ServiceAreasLakeNormanNcRouteImport } from './routes/service-areas/lake-norman-nc'
import { Route as ServiceAreasMooresvilleNcRouteImport } from './routes/service-areas/mooresville-nc'
import { Route as ServiceAreasMountMourneNcRouteImport } from './routes/service-areas/mount-mourne-nc'
import { Route as ServiceAreasSherrillsFordNcRouteImport } from './routes/service-areas/sherrills-ford-nc'
import { Route as ServiceAreasStatesvilleNcRouteImport } from './routes/service-areas/statesville-nc'
import { Route as ServiceAreasTroutmanNcRouteImport } from './routes/service-areas/troutman-nc'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesCommercialPressureWashingRouteImport } from './routes/services/commercial-pressure-washing'
import { Route as ServicesConcreteCleaningRouteImport } from './routes/services/concrete-cleaning'
import { Route as ServicesDrivewayCleaningRouteImport } from './routes/services/driveway-cleaning'
import { Route as ServicesEmergencyServiceRouteImport } from './routes/services/emergency-service'
import { Route as ServicesHouseWashingRouteImport } from './routes/services/house-washing'
import { Route as ServicesPressureWashingRouteImport } from './routes/services/pressure-washing'
import { Route as ServicesRoofCleaningRouteImport } from './routes/services/roof-cleaning'
import { Route as ServicesSoftWashingRouteImport } from './routes/services/soft-washing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcreteCleaningRoute = ConcreteCleaningRouteImport.update({
  id: '/concrete-cleaning',
  path: '/concrete-cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DrivewayCleaningRoute = DrivewayCleaningRouteImport.update({
  id: '/driveway-cleaning',
  path: '/driveway-cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PaintingServiceRoute = PaintingServiceRouteImport.update({
  id: '/painting-service',
  path: '/painting-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentialRoute = ResidentialRouteImport.update({
  id: '/residential',
  path: '/residential',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RoofWashingRoute = RoofWashingRouteImport.update({
  id: '/roof-washing',
  path: '/roof-washing',
  getParentRoute: () => rootRouteImport,
} as any)
const SidingCleaningRoute = SidingCleaningRouteImport.update({
  id: '/siding-cleaning',
  path: '/siding-cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBestTimeOfYearToPressureWashHomeMooresvilleNcRoute =
  BlogBestTimeOfYearToPressureWashHomeMooresvilleNcRouteImport.update({
    id: '/blog/best-time-of-year-to-pressure-wash-home-mooresville-nc',
    path: '/blog/best-time-of-year-to-pressure-wash-home-mooresville-nc',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCommercialPressureWashingLakeNormanRoute =
  BlogCommercialPressureWashingLakeNormanRouteImport.update({
    id: '/blog/commercial-pressure-washing-lake-norman',
    path: '/blog/commercial-pressure-washing-lake-norman',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogDumpsterPadCleaningRestaurantsLakeNormanRoute =
  BlogDumpsterPadCleaningRestaurantsLakeNormanRouteImport.update({
    id: '/blog/dumpster-pad-cleaning-restaurants-lake-norman',
    path: '/blog/dumpster-pad-cleaning-restaurants-lake-norman',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowMuchDoesPressureWashingCostMooresvilleNcRoute =
  BlogHowMuchDoesPressureWashingCostMooresvilleNcRouteImport.update({
    id: '/blog/how-much-does-pressure-washing-cost-mooresville-nc',
    path: '/blog/how-much-does-pressure-washing-cost-mooresville-nc',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowOftenToPressureWashHouseNcRoute =
  BlogHowOftenToPressureWashHouseNcRouteImport.update({
    id: '/blog/how-often-to-pressure-wash-house-nc',
    path: '/blog/how-often-to-pressure-wash-house-nc',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowToCleanConcreteDrivewayNcClayRoute =
  BlogHowToCleanConcreteDrivewayNcClayRouteImport.update({
    id: '/blog/how-to-clean-concrete-driveway-nc-clay',
    path: '/blog/how-to-clean-concrete-driveway-nc-clay',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowToRemoveAlgaeRoofLakeNormanRoute =
  BlogHowToRemoveAlgaeRoofLakeNormanRouteImport.update({
    id: '/blog/how-to-remove-algae-roof-lake-norman',
    path: '/blog/how-to-remove-algae-roof-lake-norman',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogPressureWashingVsSoftWashingRoute =
  BlogPressureWashingVsSoftWashingRouteImport.update({
    id: '/blog/pressure-washing-vs-soft-washing',
    path: '/blog/pressure-washing-vs-soft-washing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAreasIndexRoute = ServiceAreasIndexRouteImport.update({
  id: '/service-areas/',
  path: '/service-areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasCorneliusNcRoute = ServiceAreasCorneliusNcRouteImport.update({
  id: '/service-areas/cornelius-nc',
  path: '/service-areas/cornelius-nc',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasDavidsonNcRoute = ServiceAreasDavidsonNcRouteImport.update({
  id: '/service-areas/davidson-nc',
  path: '/service-areas/davidson-nc',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasDenverNcRoute = ServiceAreasDenverNcRouteImport.update({
  id: '/service-areas/denver-nc',
  path: '/service-areas/denver-nc',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasHuntersvilleNcRoute =
  ServiceAreasHuntersvilleNcRouteImport.update({
    id: '/service-areas/huntersville-nc',
    path: '/service-areas/huntersville-nc',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAreasLakeNormanNcRoute =
  ServiceAreasLakeNormanNcRouteImport.update({
    id: '/service-areas/lake-norman-nc',
    path: '/service-areas/lake-norman-nc',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAreasMooresvilleNcRoute =
  ServiceAreasMooresvilleNcRouteImport.update({
    id: '/service-areas/mooresville-nc',
    path: '/service-areas/mooresville-nc',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAreasMountMourneNcRoute =
  ServiceAreasMountMourneNcRouteImport.update({
    id: '/service-areas/mount-mourne-nc',
    path: '/service-areas/mount-mourne-nc',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAreasSherrillsFordNcRoute =
  ServiceAreasSherrillsFordNcRouteImport.update({
    id: '/service-areas/sherrills-ford-nc',
    path: '/service-areas/sherrills-ford-nc',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAreasStatesvilleNcRoute =
  ServiceAreasStatesvilleNcRouteImport.update({
    id: '/service-areas/statesville-nc',
    path: '/service-areas/statesville-nc',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAreasTroutmanNcRoute = ServiceAreasTroutmanNcRouteImport.update({
  id: '/service-areas/troutman-nc',
  path: '/service-areas/troutman-nc',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCommercialPressureWashingRoute =
  ServicesCommercialPressureWashingRouteImport.update({
    id: '/services/commercial-pressure-washing',
    path: '/services/commercial-pressure-washing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesConcreteCleaningRoute =
  ServicesConcreteCleaningRouteImport.update({
    id: '/services/concrete-cleaning',
    path: '/services/concrete-cleaning',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesDrivewayCleaningRoute =
  ServicesDrivewayCleaningRouteImport.update({
    id: '/services/driveway-cleaning',
    path: '/services/driveway-cleaning',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesEmergencyServiceRoute =
  ServicesEmergencyServiceRouteImport.update({
    id: '/services/emergency-service',
    path: '/services/emergency-service',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesHouseWashingRoute = ServicesHouseWashingRouteImport.update({
  id: '/services/house-washing',
  path: '/services/house-washing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPressureWashingRoute = ServicesPressureWashingRouteImport.update({
  id: '/services/pressure-washing',
  path: '/services/pressure-washing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoofCleaningRoute = ServicesRoofCleaningRouteImport.update({
  id: '/services/roof-cleaning',
  path: '/services/roof-cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSoftWashingRoute = ServicesSoftWashingRouteImport.update({
  id: '/services/soft-washing',
  path: '/services/soft-washing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial': typeof CommercialRoute
  '/concrete-cleaning': typeof ConcreteCleaningRoute
  '/contact': typeof ContactRoute
  '/driveway-cleaning': typeof DrivewayCleaningRoute
  '/estimate': typeof EstimateRoute
  '/gallery': typeof GalleryRoute
  '/painting-service': typeof PaintingServiceRoute
  '/privacy': typeof PrivacyRoute
  '/residential': typeof ResidentialRoute
  '/reviews': typeof ReviewsRoute
  '/roof-washing': typeof RoofWashingRoute
  '/siding-cleaning': typeof SidingCleaningRoute
  '/terms': typeof TermsRoute
  '/blog/best-time-of-year-to-pressure-wash-home-mooresville-nc': typeof BlogBestTimeOfYearToPressureWashHomeMooresvilleNcRoute
  '/blog/commercial-pressure-washing-lake-norman': typeof BlogCommercialPressureWashingLakeNormanRoute
  '/blog/dumpster-pad-cleaning-restaurants-lake-norman': typeof BlogDumpsterPadCleaningRestaurantsLakeNormanRoute
  '/blog/how-much-does-pressure-washing-cost-mooresville-nc': typeof BlogHowMuchDoesPressureWashingCostMooresvilleNcRoute
  '/blog/how-often-to-pressure-wash-house-nc': typeof BlogHowOftenToPressureWashHouseNcRoute
  '/blog/how-to-clean-concrete-driveway-nc-clay': typeof BlogHowToCleanConcreteDrivewayNcClayRoute
  '/blog/how-to-remove-algae-roof-lake-norman': typeof BlogHowToRemoveAlgaeRoofLakeNormanRoute
  '/blog/pressure-washing-vs-soft-washing': typeof BlogPressureWashingVsSoftWashingRoute
  '/service-areas/cornelius-nc': typeof ServiceAreasCorneliusNcRoute
  '/service-areas/davidson-nc': typeof ServiceAreasDavidsonNcRoute
  '/service-areas/denver-nc': typeof ServiceAreasDenverNcRoute
  '/service-areas/huntersville-nc': typeof ServiceAreasHuntersvilleNcRoute
  '/service-areas/lake-norman-nc': typeof ServiceAreasLakeNormanNcRoute
  '/service-areas/mooresville-nc': typeof ServiceAreasMooresvilleNcRoute
  '/service-areas/mount-mourne-nc': typeof ServiceAreasMountMourneNcRoute
  '/service-areas/sherrills-ford-nc': typeof ServiceAreasSherrillsFordNcRoute
  '/service-areas/statesville-nc': typeof ServiceAreasStatesvilleNcRoute
  '/service-areas/troutman-nc': typeof ServiceAreasTroutmanNcRoute
  '/services/commercial-pressure-washing': typeof ServicesCommercialPressureWashingRoute
  '/services/concrete-cleaning': typeof ServicesConcreteCleaningRoute
  '/services/driveway-cleaning': typeof ServicesDrivewayCleaningRoute
  '/services/emergency-service': typeof ServicesEmergencyServiceRoute
  '/services/house-washing': typeof ServicesHouseWashingRoute
  '/services/pressure-washing': typeof ServicesPressureWashingRoute
  '/services/roof-cleaning': typeof ServicesRoofCleaningRoute
  '/services/soft-washing': typeof ServicesSoftWashingRoute
  '/blog/': typeof BlogIndexRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial': typeof CommercialRoute
  '/concrete-cleaning': typeof ConcreteCleaningRoute
  '/contact': typeof ContactRoute
  '/driveway-cleaning': typeof DrivewayCleaningRoute
  '/estimate': typeof EstimateRoute
  '/gallery': typeof GalleryRoute
  '/painting-service': typeof PaintingServiceRoute
  '/privacy': typeof PrivacyRoute
  '/residential': typeof ResidentialRoute
  '/reviews': typeof ReviewsRoute
  '/roof-washing': typeof RoofWashingRoute
  '/siding-cleaning': typeof SidingCleaningRoute
  '/terms': typeof TermsRoute
  '/blog/best-time-of-year-to-pressure-wash-home-mooresville-nc': typeof BlogBestTimeOfYearToPressureWashHomeMooresvilleNcRoute
  '/blog/commercial-pressure-washing-lake-norman': typeof BlogCommercialPressureWashingLakeNormanRoute
  '/blog/dumpster-pad-cleaning-restaurants-lake-norman': typeof BlogDumpsterPadCleaningRestaurantsLakeNormanRoute
  '/blog/how-much-does-pressure-washing-cost-mooresville-nc': typeof BlogHowMuchDoesPressureWashingCostMooresvilleNcRoute
  '/blog/how-often-to-pressure-wash-house-nc': typeof BlogHowOftenToPressureWashHouseNcRoute
  '/blog/how-to-clean-concrete-driveway-nc-clay': typeof BlogHowToCleanConcreteDrivewayNcClayRoute
  '/blog/how-to-remove-algae-roof-lake-norman': typeof BlogHowToRemoveAlgaeRoofLakeNormanRoute
  '/blog/pressure-washing-vs-soft-washing': typeof BlogPressureWashingVsSoftWashingRoute
  '/service-areas/cornelius-nc': typeof ServiceAreasCorneliusNcRoute
  '/service-areas/davidson-nc': typeof ServiceAreasDavidsonNcRoute
  '/service-areas/denver-nc': typeof ServiceAreasDenverNcRoute
  '/service-areas/huntersville-nc': typeof ServiceAreasHuntersvilleNcRoute
  '/service-areas/lake-norman-nc': typeof ServiceAreasLakeNormanNcRoute
  '/service-areas/mooresville-nc': typeof ServiceAreasMooresvilleNcRoute
  '/service-areas/mount-mourne-nc': typeof ServiceAreasMountMourneNcRoute
  '/service-areas/sherrills-ford-nc': typeof ServiceAreasSherrillsFordNcRoute
  '/service-areas/statesville-nc': typeof ServiceAreasStatesvilleNcRoute
  '/service-areas/troutman-nc': typeof ServiceAreasTroutmanNcRoute
  '/services/commercial-pressure-washing': typeof ServicesCommercialPressureWashingRoute
  '/services/concrete-cleaning': typeof ServicesConcreteCleaningRoute
  '/services/driveway-cleaning': typeof ServicesDrivewayCleaningRoute
  '/services/emergency-service': typeof ServicesEmergencyServiceRoute
  '/services/house-washing': typeof ServicesHouseWashingRoute
  '/services/pressure-washing': typeof ServicesPressureWashingRoute
  '/services/roof-cleaning': typeof ServicesRoofCleaningRoute
  '/services/soft-washing': typeof ServicesSoftWashingRoute
  '/blog': typeof BlogIndexRoute
  '/service-areas': typeof ServiceAreasIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial': typeof CommercialRoute
  '/concrete-cleaning': typeof ConcreteCleaningRoute
  '/contact': typeof ContactRoute
  '/driveway-cleaning': typeof DrivewayCleaningRoute
  '/estimate': typeof EstimateRoute
  '/gallery': typeof GalleryRoute
  '/painting-service': typeof PaintingServiceRoute
  '/privacy': typeof PrivacyRoute
  '/residential': typeof ResidentialRoute
  '/reviews': typeof ReviewsRoute
  '/roof-washing': typeof RoofWashingRoute
  '/siding-cleaning': typeof SidingCleaningRoute
  '/terms': typeof TermsRoute
  '/blog/best-time-of-year-to-pressure-wash-home-mooresville-nc': typeof BlogBestTimeOfYearToPressureWashHomeMooresvilleNcRoute
  '/blog/commercial-pressure-washing-lake-norman': typeof BlogCommercialPressureWashingLakeNormanRoute
  '/blog/dumpster-pad-cleaning-restaurants-lake-norman': typeof BlogDumpsterPadCleaningRestaurantsLakeNormanRoute
  '/blog/how-much-does-pressure-washing-cost-mooresville-nc': typeof BlogHowMuchDoesPressureWashingCostMooresvilleNcRoute
  '/blog/how-often-to-pressure-wash-house-nc': typeof BlogHowOftenToPressureWashHouseNcRoute
  '/blog/how-to-clean-concrete-driveway-nc-clay': typeof BlogHowToCleanConcreteDrivewayNcClayRoute
  '/blog/how-to-remove-algae-roof-lake-norman': typeof BlogHowToRemoveAlgaeRoofLakeNormanRoute
  '/blog/pressure-washing-vs-soft-washing': typeof BlogPressureWashingVsSoftWashingRoute
  '/service-areas/cornelius-nc': typeof ServiceAreasCorneliusNcRoute
  '/service-areas/davidson-nc': typeof ServiceAreasDavidsonNcRoute
  '/service-areas/denver-nc': typeof ServiceAreasDenverNcRoute
  '/service-areas/huntersville-nc': typeof ServiceAreasHuntersvilleNcRoute
  '/service-areas/lake-norman-nc': typeof ServiceAreasLakeNormanNcRoute
  '/service-areas/mooresville-nc': typeof ServiceAreasMooresvilleNcRoute
  '/service-areas/mount-mourne-nc': typeof ServiceAreasMountMourneNcRoute
  '/service-areas/sherrills-ford-nc': typeof ServiceAreasSherrillsFordNcRoute
  '/service-areas/statesville-nc': typeof ServiceAreasStatesvilleNcRoute
  '/service-areas/troutman-nc': typeof ServiceAreasTroutmanNcRoute
  '/services/commercial-pressure-washing': typeof ServicesCommercialPressureWashingRoute
  '/services/concrete-cleaning': typeof ServicesConcreteCleaningRoute
  '/services/driveway-cleaning': typeof ServicesDrivewayCleaningRoute
  '/services/emergency-service': typeof ServicesEmergencyServiceRoute
  '/services/house-washing': typeof ServicesHouseWashingRoute
  '/services/pressure-washing': typeof ServicesPressureWashingRoute
  '/services/roof-cleaning': typeof ServicesRoofCleaningRoute
  '/services/soft-washing': typeof ServicesSoftWashingRoute
  '/blog/': typeof BlogIndexRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/commercial'
    | '/concrete-cleaning'
    | '/contact'
    | '/driveway-cleaning'
    | '/estimate'
    | '/gallery'
    | '/painting-service'
    | '/privacy'
    | '/residential'
    | '/reviews'
    | '/roof-washing'
    | '/siding-cleaning'
    | '/terms'
    | '/blog/best-time-of-year-to-pressure-wash-home-mooresville-nc'
    | '/blog/commercial-pressure-washing-lake-norman'
    | '/blog/dumpster-pad-cleaning-restaurants-lake-norman'
    | '/blog/how-much-does-pressure-washing-cost-mooresville-nc'
    | '/blog/how-often-to-pressure-wash-house-nc'
    | '/blog/how-to-clean-concrete-driveway-nc-clay'
    | '/blog/how-to-remove-algae-roof-lake-norman'
    | '/blog/pressure-washing-vs-soft-washing'
    | '/service-areas/cornelius-nc'
    | '/service-areas/davidson-nc'
    | '/service-areas/denver-nc'
    | '/service-areas/huntersville-nc'
    | '/service-areas/lake-norman-nc'
    | '/service-areas/mooresville-nc'
    | '/service-areas/mount-mourne-nc'
    | '/service-areas/sherrills-ford-nc'
    | '/service-areas/statesville-nc'
    | '/service-areas/troutman-nc'
    | '/services/commercial-pressure-washing'
    | '/services/concrete-cleaning'
    | '/services/driveway-cleaning'
    | '/services/emergency-service'
    | '/services/house-washing'
    | '/services/pressure-washing'
    | '/services/roof-cleaning'
    | '/services/soft-washing'
    | '/blog/'
    | '/service-areas/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/commercial'
    | '/concrete-cleaning'
    | '/contact'
    | '/driveway-cleaning'
    | '/estimate'
    | '/gallery'
    | '/painting-service'
    | '/privacy'
    | '/residential'
    | '/reviews'
    | '/roof-washing'
    | '/siding-cleaning'
    | '/terms'
    | '/blog/best-time-of-year-to-pressure-wash-home-mooresville-nc'
    | '/blog/commercial-pressure-washing-lake-norman'
    | '/blog/dumpster-pad-cleaning-restaurants-lake-norman'
    | '/blog/how-much-does-pressure-washing-cost-mooresville-nc'
    | '/blog/how-often-to-pressure-wash-house-nc'
    | '/blog/how-to-clean-concrete-driveway-nc-clay'
    | '/blog/how-to-remove-algae-roof-lake-norman'
    | '/blog/pressure-washing-vs-soft-washing'
    | '/service-areas/cornelius-nc'
    | '/service-areas/davidson-nc'
    | '/service-areas/denver-nc'
    | '/service-areas/huntersville-nc'
    | '/service-areas/lake-norman-nc'
    | '/service-areas/mooresville-nc'
    | '/service-areas/mount-mourne-nc'
    | '/service-areas/sherrills-ford-nc'
    | '/service-areas/statesville-nc'
    | '/service-areas/troutman-nc'
    | '/services/commercial-pressure-washing'
    | '/services/concrete-cleaning'
    | '/services/driveway-cleaning'
    | '/services/emergency-service'
    | '/services/house-washing'
    | '/services/pressure-washing'
    | '/services/roof-cleaning'
    | '/services/soft-washing'
    | '/blog'
    | '/service-areas'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/commercial'
    | '/concrete-cleaning'
    | '/contact'
    | '/driveway-cleaning'
    | '/estimate'
    | '/gallery'
    | '/painting-service'
    | '/privacy'
    | '/residential'
    | '/reviews'
    | '/roof-washing'
    | '/siding-cleaning'
    | '/terms'
    | '/blog/best-time-of-year-to-pressure-wash-home-mooresville-nc'
    | '/blog/commercial-pressure-washing-lake-norman'
    | '/blog/dumpster-pad-cleaning-restaurants-lake-norman'
    | '/blog/how-much-does-pressure-washing-cost-mooresville-nc'
    | '/blog/how-often-to-pressure-wash-house-nc'
    | '/blog/how-to-clean-concrete-driveway-nc-clay'
    | '/blog/how-to-remove-algae-roof-lake-norman'
    | '/blog/pressure-washing-vs-soft-washing'
    | '/service-areas/cornelius-nc'
    | '/service-areas/davidson-nc'
    | '/service-areas/denver-nc'
    | '/service-areas/huntersville-nc'
    | '/service-areas/lake-norman-nc'
    | '/service-areas/mooresville-nc'
    | '/service-areas/mount-mourne-nc'
    | '/service-areas/sherrills-ford-nc'
    | '/service-areas/statesville-nc'
    | '/service-areas/troutman-nc'
    | '/services/commercial-pressure-washing'
    | '/services/concrete-cleaning'
    | '/services/driveway-cleaning'
    | '/services/emergency-service'
    | '/services/house-washing'
    | '/services/pressure-washing'
    | '/services/roof-cleaning'
    | '/services/soft-washing'
    | '/blog/'
    | '/service-areas/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommercialRoute: typeof CommercialRoute
  ConcreteCleaningRoute: typeof ConcreteCleaningRoute
  ContactRoute: typeof ContactRoute
  DrivewayCleaningRoute: typeof DrivewayCleaningRoute
  EstimateRoute: typeof EstimateRoute
  GalleryRoute: typeof GalleryRoute
  PaintingServiceRoute: typeof PaintingServiceRoute
  PrivacyRoute: typeof PrivacyRoute
  ResidentialRoute: typeof ResidentialRoute
  ReviewsRoute: typeof ReviewsRoute
  RoofWashingRoute: typeof RoofWashingRoute
  SidingCleaningRoute: typeof SidingCleaningRoute
  TermsRoute: typeof TermsRoute
  BlogBestTimeOfYearToPressureWashHomeMooresvilleNcRoute: typeof BlogBestTimeOfYearToPressureWashHomeMooresvilleNcRoute
  BlogCommercialPressureWashingLakeNormanRoute: typeof BlogCommercialPressureWashingLakeNormanRoute
  BlogDumpsterPadCleaningRestaurantsLakeNormanRoute: typeof BlogDumpsterPadCleaningRestaurantsLakeNormanRoute
  BlogHowMuchDoesPressureWashingCostMooresvilleNcRoute: typeof BlogHowMuchDoesPressureWashingCostMooresvilleNcRoute
  BlogHowOftenToPressureWashHouseNcRoute: typeof BlogHowOftenToPressureWashHouseNcRoute
  BlogHowToCleanConcreteDrivewayNcClayRoute: typeof BlogHowToCleanConcreteDrivewayNcClayRoute
  BlogHowToRemoveAlgaeRoofLakeNormanRoute: typeof BlogHowToRemoveAlgaeRoofLakeNormanRoute
  BlogPressureWashingVsSoftWashingRoute: typeof BlogPressureWashingVsSoftWashingRoute
  ServiceAreasCorneliusNcRoute: typeof ServiceAreasCorneliusNcRoute
  ServiceAreasDavidsonNcRoute: typeof ServiceAreasDavidsonNcRoute
  ServiceAreasDenverNcRoute: typeof ServiceAreasDenverNcRoute
  ServiceAreasHuntersvilleNcRoute: typeof ServiceAreasHuntersvilleNcRoute
  ServiceAreasLakeNormanNcRoute: typeof ServiceAreasLakeNormanNcRoute
  ServiceAreasMooresvilleNcRoute: typeof ServiceAreasMooresvilleNcRoute
  ServiceAreasMountMourneNcRoute: typeof ServiceAreasMountMourneNcRoute
  ServiceAreasSherrillsFordNcRoute: typeof ServiceAreasSherrillsFordNcRoute
  ServiceAreasStatesvilleNcRoute: typeof ServiceAreasStatesvilleNcRoute
  ServiceAreasTroutmanNcRoute: typeof ServiceAreasTroutmanNcRoute
  ServicesCommercialPressureWashingRoute: typeof ServicesCommercialPressureWashingRoute
  ServicesConcreteCleaningRoute: typeof ServicesConcreteCleaningRoute
  ServicesDrivewayCleaningRoute: typeof ServicesDrivewayCleaningRoute
  ServicesEmergencyServiceRoute: typeof ServicesEmergencyServiceRoute
  ServicesHouseWashingRoute: typeof ServicesHouseWashingRoute
  ServicesPressureWashingRoute: typeof ServicesPressureWashingRoute
  ServicesRoofCleaningRoute: typeof ServicesRoofCleaningRoute
  ServicesSoftWashingRoute: typeof ServicesSoftWashingRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServiceAreasIndexRoute: typeof ServiceAreasIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concrete-cleaning': {
      id: '/concrete-cleaning'
      path: '/concrete-cleaning'
      fullPath: '/concrete-cleaning'
      preLoaderRoute: typeof ConcreteCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driveway-cleaning': {
      id: '/driveway-cleaning'
      path: '/driveway-cleaning'
      fullPath: '/driveway-cleaning'
      preLoaderRoute: typeof DrivewayCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painting-service': {
      id: '/painting-service'
      path: '/painting-service'
      fullPath: '/painting-service'
      preLoaderRoute: typeof PaintingServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residential': {
      id: '/residential'
      path: '/residential'
      fullPath: '/residential'
      preLoaderRoute: typeof ResidentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roof-washing': {
      id: '/roof-washing'
      path: '/roof-washing'
      fullPath: '/roof-washing'
      preLoaderRoute: typeof RoofWashingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siding-cleaning': {
      id: '/siding-cleaning'
      path: '/siding-cleaning'
      fullPath: '/siding-cleaning'
      preLoaderRoute: typeof SidingCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/best-time-of-year-to-pressure-wash-home-mooresville-nc': {
      id: '/blog/best-time-of-year-to-pressure-wash-home-mooresville-nc'
      path: '/blog/best-time-of-year-to-pressure-wash-home-mooresville-nc'
      fullPath: '/blog/best-time-of-year-to-pressure-wash-home-mooresville-nc'
      preLoaderRoute: typeof BlogBestTimeOfYearToPressureWashHomeMooresvilleNcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/commercial-pressure-washing-lake-norman': {
      id: '/blog/commercial-pressure-washing-lake-norman'
      path: '/blog/commercial-pressure-washing-lake-norman'
      fullPath: '/blog/commercial-pressure-washing-lake-norman'
      preLoaderRoute: typeof BlogCommercialPressureWashingLakeNormanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/dumpster-pad-cleaning-restaurants-lake-norman': {
      id: '/blog/dumpster-pad-cleaning-restaurants-lake-norman'
      path: '/blog/dumpster-pad-cleaning-restaurants-lake-norman'
      fullPath: '/blog/dumpster-pad-cleaning-restaurants-lake-norman'
      preLoaderRoute: typeof BlogDumpsterPadCleaningRestaurantsLakeNormanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-much-does-pressure-washing-cost-mooresville-nc': {
      id: '/blog/how-much-does-pressure-washing-cost-mooresville-nc'
      path: '/blog/how-much-does-pressure-washing-cost-mooresville-nc'
      fullPath: '/blog/how-much-does-pressure-washing-cost-mooresville-nc'
      preLoaderRoute: typeof BlogHowMuchDoesPressureWashingCostMooresvilleNcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-often-to-pressure-wash-house-nc': {
      id: '/blog/how-often-to-pressure-wash-house-nc'
      path: '/blog/how-often-to-pressure-wash-house-nc'
      fullPath: '/blog/how-often-to-pressure-wash-house-nc'
      preLoaderRoute: typeof BlogHowOftenToPressureWashHouseNcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-clean-concrete-driveway-nc-clay': {
      id: '/blog/how-to-clean-concrete-driveway-nc-clay'
      path: '/blog/how-to-clean-concrete-driveway-nc-clay'
      fullPath: '/blog/how-to-clean-concrete-driveway-nc-clay'
      preLoaderRoute: typeof BlogHowToCleanConcreteDrivewayNcClayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-remove-algae-roof-lake-norman': {
      id: '/blog/how-to-remove-algae-roof-lake-norman'
      path: '/blog/how-to-remove-algae-roof-lake-norman'
      fullPath: '/blog/how-to-remove-algae-roof-lake-norman'
      preLoaderRoute: typeof BlogHowToRemoveAlgaeRoofLakeNormanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/pressure-washing-vs-soft-washing': {
      id: '/blog/pressure-washing-vs-soft-washing'
      path: '/blog/pressure-washing-vs-soft-washing'
      fullPath: '/blog/pressure-washing-vs-soft-washing'
      preLoaderRoute: typeof BlogPressureWashingVsSoftWashingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/': {
      id: '/service-areas/'
      path: '/service-areas'
      fullPath: '/service-areas/'
      preLoaderRoute: typeof ServiceAreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/cornelius-nc': {
      id: '/service-areas/cornelius-nc'
      path: '/service-areas/cornelius-nc'
      fullPath: '/service-areas/cornelius-nc'
      preLoaderRoute: typeof ServiceAreasCorneliusNcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/davidson-nc': {
      id: '/service-areas/davidson-nc'
      path: '/service-areas/davidson-nc'
      fullPath: '/service-areas/davidson-nc'
      preLoaderRoute: typeof ServiceAreasDavidsonNcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/denver-nc': {
      id: '/service-areas/denver-nc'
      path: '/service-areas/denver-nc'
      fullPath: '/service-areas/denver-nc'
      preLoaderRoute: typeof ServiceAreasDenverNcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/huntersville-nc': {
      id: '/service-areas/huntersville-nc'
      path: '/service-areas/huntersville-nc'
      fullPath: '/service-areas/huntersville-nc'
      preLoaderRoute: typeof ServiceAreasHuntersvilleNcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/lake-norman-nc': {
      id: '/service-areas/lake-norman-nc'
      path: '/service-areas/lake-norman-nc'
      fullPath: '/service-areas/lake-norman-nc'
      preLoaderRoute: typeof ServiceAreasLakeNormanNcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/mooresville-nc': {
      id: '/service-areas/mooresville-nc'
      path: '/service-areas/mooresville-nc'
      fullPath: '/service-areas/mooresville-nc'
      preLoaderRoute: typeof ServiceAreasMooresvilleNcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/mount-mourne-nc': {
      id: '/service-areas/mount-mourne-nc'
      path: '/service-areas/mount-mourne-nc'
      fullPath: '/service-areas/mount-mourne-nc'
      preLoaderRoute: typeof ServiceAreasMountMourneNcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/sherrills-ford-nc': {
      id: '/service-areas/sherrills-ford-nc'
      path: '/service-areas/sherrills-ford-nc'
      fullPath: '/service-areas/sherrills-ford-nc'
      preLoaderRoute: typeof ServiceAreasSherrillsFordNcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/statesville-nc': {
      id: '/service-areas/statesville-nc'
      path: '/service-areas/statesville-nc'
      fullPath: '/service-areas/statesville-nc'
      preLoaderRoute: typeof ServiceAreasStatesvilleNcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/troutman-nc': {
      id: '/service-areas/troutman-nc'
      path: '/service-areas/troutman-nc'
      fullPath: '/service-areas/troutman-nc'
      preLoaderRoute: typeof ServiceAreasTroutmanNcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/commercial-pressure-washing': {
      id: '/services/commercial-pressure-washing'
      path: '/services/commercial-pressure-washing'
      fullPath: '/services/commercial-pressure-washing'
      preLoaderRoute: typeof ServicesCommercialPressureWashingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/concrete-cleaning': {
      id: '/services/concrete-cleaning'
      path: '/services/concrete-cleaning'
      fullPath: '/services/concrete-cleaning'
      preLoaderRoute: typeof ServicesConcreteCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/driveway-cleaning': {
      id: '/services/driveway-cleaning'
      path: '/services/driveway-cleaning'
      fullPath: '/services/driveway-cleaning'
      preLoaderRoute: typeof ServicesDrivewayCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/emergency-service': {
      id: '/services/emergency-service'
      path: '/services/emergency-service'
      fullPath: '/services/emergency-service'
      preLoaderRoute: typeof ServicesEmergencyServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/house-washing': {
      id: '/services/house-washing'
      path: '/services/house-washing'
      fullPath: '/services/house-washing'
      preLoaderRoute: typeof ServicesHouseWashingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/pressure-washing': {
      id: '/services/pressure-washing'
      path: '/services/pressure-washing'
      fullPath: '/services/pressure-washing'
      preLoaderRoute: typeof ServicesPressureWashingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/roof-cleaning': {
      id: '/services/roof-cleaning'
      path: '/services/roof-cleaning'
      fullPath: '/services/roof-cleaning'
      preLoaderRoute: typeof ServicesRoofCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/soft-washing': {
      id: '/services/soft-washing'
      path: '/services/soft-washing'
      fullPath: '/services/soft-washing'
      preLoaderRoute: typeof ServicesSoftWashingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommercialRoute: CommercialRoute,
  ConcreteCleaningRoute: ConcreteCleaningRoute,
  ContactRoute: ContactRoute,
  DrivewayCleaningRoute: DrivewayCleaningRoute,
  EstimateRoute: EstimateRoute,
  GalleryRoute: GalleryRoute,
  PaintingServiceRoute: PaintingServiceRoute,
  PrivacyRoute: PrivacyRoute,
  ResidentialRoute: ResidentialRoute,
  ReviewsRoute: ReviewsRoute,
  RoofWashingRoute: RoofWashingRoute,
  SidingCleaningRoute: SidingCleaningRoute,
  TermsRoute: TermsRoute,
  BlogBestTimeOfYearToPressureWashHomeMooresvilleNcRoute:
    BlogBestTimeOfYearToPressureWashHomeMooresvilleNcRoute,
  BlogCommercialPressureWashingLakeNormanRoute:
    BlogCommercialPressureWashingLakeNormanRoute,
  BlogDumpsterPadCleaningRestaurantsLakeNormanRoute:
    BlogDumpsterPadCleaningRestaurantsLakeNormanRoute,
  BlogHowMuchDoesPressureWashingCostMooresvilleNcRoute:
    BlogHowMuchDoesPressureWashingCostMooresvilleNcRoute,
  BlogHowOftenToPressureWashHouseNcRoute:
    BlogHowOftenToPressureWashHouseNcRoute,
  BlogHowToCleanConcreteDrivewayNcClayRoute:
    BlogHowToCleanConcreteDrivewayNcClayRoute,
  BlogHowToRemoveAlgaeRoofLakeNormanRoute:
    BlogHowToRemoveAlgaeRoofLakeNormanRoute,
  BlogPressureWashingVsSoftWashingRoute: BlogPressureWashingVsSoftWashingRoute,
  ServiceAreasCorneliusNcRoute: ServiceAreasCorneliusNcRoute,
  ServiceAreasDavidsonNcRoute: ServiceAreasDavidsonNcRoute,
  ServiceAreasDenverNcRoute: ServiceAreasDenverNcRoute,
  ServiceAreasHuntersvilleNcRoute: ServiceAreasHuntersvilleNcRoute,
  ServiceAreasLakeNormanNcRoute: ServiceAreasLakeNormanNcRoute,
  ServiceAreasMooresvilleNcRoute: ServiceAreasMooresvilleNcRoute,
  ServiceAreasMountMourneNcRoute: ServiceAreasMountMourneNcRoute,
  ServiceAreasSherrillsFordNcRoute: ServiceAreasSherrillsFordNcRoute,
  ServiceAreasStatesvilleNcRoute: ServiceAreasStatesvilleNcRoute,
  ServiceAreasTroutmanNcRoute: ServiceAreasTroutmanNcRoute,
  ServicesCommercialPressureWashingRoute:
    ServicesCommercialPressureWashingRoute,
  ServicesConcreteCleaningRoute: ServicesConcreteCleaningRoute,
  ServicesDrivewayCleaningRoute: ServicesDrivewayCleaningRoute,
  ServicesEmergencyServiceRoute: ServicesEmergencyServiceRoute,
  ServicesHouseWashingRoute: ServicesHouseWashingRoute,
  ServicesPressureWashingRoute: ServicesPressureWashingRoute,
  ServicesRoofCleaningRoute: ServicesRoofCleaningRoute,
  ServicesSoftWashingRoute: ServicesSoftWashingRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServiceAreasIndexRoute: ServiceAreasIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
